//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int idActividad { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public string asunto { get; set; }
        public Nullable<int> idObjetivo { get; set; }
        public Nullable<int> idPrioridad { get; set; }
        public Nullable<int> idTipoActividad { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idResponsable { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFin { get; set; }
        public Nullable<System.TimeSpan> tiempoReal { get; set; }
        public string alerta { get; set; }
        public string estado { get; set; }
        public string resultado { get; set; }
        public string direccion { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Cuenta Cuenta { get; set; }
        public virtual Objetivo Objetivo { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
    }
}
