//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int nombre { get; set; }
        public string logo { get; set; }
        public string direccion { get; set; }
        public string web { get; set; }
        public string resumenEjectutivo { get; set; }
    }
}
