//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propuesta
    {
        public int idPropuesta { get; set; }
        public int idOpurtunidadNegocio { get; set; }
        public System.DateTime fecha { get; set; }
        public string nroPropuesta { get; set; }
        public string alcancePropuesta { get; set; }
        public string incluyeCapacitacion { get; set; }
        public string incluyeInstalacion { get; set; }
        public string incluyeSoporte { get; set; }
        public string conFactura { get; set; }
        public System.TimeSpan tiempoImplementacion { get; set; }
        public decimal CostoImplementacion { get; set; }
        public string FormaPago { get; set; }
        public decimal Ganancia { get; set; }
        public string estado { get; set; }
    
        public virtual OportunidadNegocio OportunidadNegocio { get; set; }
    }
}
